[toolchain]
profile = "default"
channel = "stable"
components = ["rust-analyzer"]
targets = [
  "x86_64-unknown-linux-gnu",
  "i686-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
  "i686-pc-windows-msvc",
  "x86_64-pc-windows-gnu",
  "i686-pc-windows-gnu",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
]